//! Report types and markdown rendering.

use std::path::Path;

/// One row in the conformance report table.
#[derive(Debug, Clone)]
pub struct Row {
    /// Fork name (e.g. `phase0`).
    pub fork: String,
    /// Test category (e.g. `ssz_generic`, `ssz_static`).
    pub category: String,
    /// Preset name, or `-` for preset-independent categories.
    pub preset: String,
    /// Number of passing test cases, or `None` for unimplemented categories.
    pub pass: Option<u64>,
    /// Number of failing test cases.
    pub fail: Option<u64>,
    /// Number of skipped test cases.
    pub skip: Option<u64>,
    /// Total test cases run.
    pub total: Option<u64>,
}

impl Row {
    /// Build a placeholder row for a category not yet implemented.
    pub fn placeholder(fork: &str, category: &str, preset: &str) -> Self {
        Self {
            fork: fork.into(),
            category: category.into(),
            preset: preset.into(),
            pass: None,
            fail: None,
            skip: None,
            total: None,
        }
    }

    /// Build a live row with numeric counts.
    pub fn live(fork: &str, category: &str, preset: &str, pass: u64, fail: u64, skip: u64) -> Self {
        Self {
            fork: fork.into(),
            category: category.into(),
            preset: preset.into(),
            pass: Some(pass),
            fail: Some(fail),
            skip: Some(skip),
            total: Some(pass + fail + skip),
        }
    }

    /// Whether this row records any failures.
    pub fn has_failures(&self) -> bool {
        self.fail.map(|f| f > 0).unwrap_or(false)
    }
}

/// Full conformance report.
#[derive(Debug, Default)]
pub struct Report {
    pub rows: Vec<Row>,
    /// Individual failure descriptions (case path + error).
    pub failures: Vec<String>,
    /// Fixtures directory that was scanned.
    pub fixtures_path: String,
    /// Spec-tests release tag, read from `<fixtures>/tag` if present.
    pub tag: String,
    /// ISO date of the run.
    pub date: String,
}

impl Report {
    /// Whether any implemented row has failures.
    pub fn has_failures(&self) -> bool {
        self.rows.iter().any(|r| r.has_failures())
    }
}

fn cell(v: Option<u64>) -> String {
    match v {
        Some(n) => n.to_string(),
        None => "-".into(),
    }
}

/// Write `docs/conformance.md` (or any target path).
pub fn write_markdown(report: &Report, path: &Path) -> std::io::Result<()> {
    let mut out = String::new();

    out.push_str("# Pharos conformance report\n\n");
    out.push_str(&format!(
        "Generated by `pharos-conformance` against `{}` on {}.\n",
        report.fixtures_path, report.date,
    ));
    if !report.tag.is_empty() {
        out.push_str(&format!(
            "Source: consensus-specs release `{}`.\n",
            report.tag
        ));
    }
    out.push('\n');

    // Table header
    out.push_str("| Fork      | Category           | Preset  | Pass | Fail | Skip | Total |\n");
    out.push_str("|-----------|--------------------|---------|------|------|------|-------|\n");

    for row in &report.rows {
        out.push_str(&format!(
            "| {:<9} | {:<18} | {:<7} | {:<4} | {:<4} | {:<4} | {:<5} |\n",
            row.fork,
            row.category,
            row.preset,
            cell(row.pass),
            cell(row.fail),
            cell(row.skip),
            cell(row.total),
        ));
    }

    // Failures section
    if !report.failures.is_empty() {
        out.push_str("\n## Failures\n\n");
        const MAX_SHOWN: usize = 50;
        let shown = report.failures.len().min(MAX_SHOWN);
        for f in &report.failures[..shown] {
            out.push_str(&format!("- {f}\n"));
        }
        if report.failures.len() > MAX_SHOWN {
            let extra = report.failures.len() - MAX_SHOWN;
            out.push_str(&format!("- ...and {extra} more\n"));
        }
    }

    std::fs::write(path, out)
}

/// Print the report table to stdout.
pub fn print_report(report: &Report) {
    println!(
        "\npharos-conformance — fixtures: {} — date: {}",
        report.fixtures_path, report.date,
    );
    if !report.tag.is_empty() {
        println!("consensus-specs release: {}", report.tag);
    }
    println!();
    println!(
        "{:<12} {:<20} {:<8} {:>5} {:>5} {:>5} {:>6}",
        "Fork", "Category", "Preset", "Pass", "Fail", "Skip", "Total"
    );
    println!("{}", "-".repeat(65));
    for row in &report.rows {
        println!(
            "{:<12} {:<20} {:<8} {:>5} {:>5} {:>5} {:>6}",
            row.fork,
            row.category,
            row.preset,
            cell(row.pass),
            cell(row.fail),
            cell(row.skip),
            cell(row.total),
        );
    }
    if !report.failures.is_empty() {
        println!("\nFailures ({}):", report.failures.len());
        for f in report.failures.iter().take(10) {
            println!("  {f}");
        }
        if report.failures.len() > 10 {
            println!("  ...and {} more", report.failures.len() - 10);
        }
    }
}
