[package]
name = "pharos-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Storage abstraction (Store trait) and rocksdb backend for Pharos."

[dependencies]
rocksdb = { workspace = true }
pharos-ssz = { workspace = true }
pharos-types = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
