[package]
name = "pharos-ssz"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "In-house SSZ encoding, decoding, and Merkleization for Pharos."

[dependencies]
pharos-utils.workspace = true
pharos-ssz-derive.workspace = true
thiserror.workspace = true
rayon.workspace = true

[dev-dependencies]
proptest.workspace = true
snap.workspace = true
serde_yaml_ng.workspace = true
criterion = { workspace = true }
pharos-types = { path = "../pharos-types" }

[[bench]]
name = "tree_hash_beacon_state"
harness = false
