[package]
name = "pharos-stf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Beacon-chain state transition function for Pharos."

[dependencies]
pharos-types.workspace = true
pharos-ssz.workspace = true
pharos-utils.workspace = true
pharos-storage.workspace = true
pharos-kzg.workspace = true
thiserror.workspace = true
rayon.workspace = true

[dev-dependencies]
snap.workspace = true
criterion = { workspace = true }

[[bench]]
name = "process_block"
harness = false
