[package]
name = "pharos-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Pharos beacon-chain types (per-fork containers, EthSpec, primitives)."

[dependencies]
pharos-utils.workspace = true
pharos-ssz.workspace = true
pharos-ssz-derive.workspace = true
thiserror.workspace = true
lru.workspace = true
parking_lot.workspace = true

[dev-dependencies]
snap.workspace = true
